// <auto-generated />
namespace CarShopIdentityManagementMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Puttingfirstnameandlastnameonregistrationpage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Puttingfirstnameandlastnameonregistrationpage));
        
        string IMigrationMetadata.Id
        {
            get { return "202404032241495_Putting first name and last name on registration page."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
